### ISSUE TITLE
API for Embrace

### ISSUE THREAD

**Issue by Sofianebenabdallah** [empatica/empatica.github.io#2]
Hello,

does this API only work with the Wristband ? Not Embrace ?

Regards,

**Comment by alecha** [comment]
Hi @Sofianebenabdallah , the SDK works only with our E4 wristband

**Comment by rodrigo05** [comment]
@alecha!
Do you have a SDK to work with Embrace 2? I need it, to obtain the EDA data, using this!
Kind Regards
